In [1]:
import numpy as np

In [25]:
X = np.random.random((10, 3))

In [26]:
X

array([[0.50582775, 0.49217474, 0.91805235],
       [0.41475947, 0.13218041, 0.42132889],
       [0.41190367, 0.90674228, 0.77187894],
       [0.74809596, 0.31380248, 0.79749731],
       [0.05539872, 0.90848913, 0.66673808],
       [0.59004992, 0.42477464, 0.87756064],
       [0.44036232, 0.01221225, 0.21298723],
       [0.92549976, 0.64937951, 0.37726458],
       [0.73705479, 0.28657635, 0.64132732],
       [0.36681553, 0.01465405, 0.94955904]])

In [27]:
X.mean(0)

array([0.51957679, 0.41409858, 0.66341944])

El 0 indica que se va a hacer por columnas

In [28]:
X.mean(1)

array([0.63868495, 0.32275626, 0.69684163, 0.61979858, 0.54354198,
       0.63079507, 0.22185393, 0.65071462, 0.55498615, 0.44367621])

El 1 te hace la media de cada fila

In [29]:
Xmean = X.mean(0)

In [30]:
X_centered = X - Xmean

In [31]:
X_centered

array([[-0.01374904,  0.07807615,  0.25463292],
       [-0.10481732, -0.28191818, -0.24209055],
       [-0.10767312,  0.49264369,  0.1084595 ],
       [ 0.22851918, -0.10029611,  0.13407787],
       [-0.46417807,  0.49439055,  0.00331864],
       [ 0.07047313,  0.01067606,  0.2141412 ],
       [-0.07921447, -0.40188634, -0.45043221],
       [ 0.40592298,  0.23528093, -0.28615486],
       [ 0.217478  , -0.12752223, -0.02209212],
       [-0.15276126, -0.39944454,  0.28613961]])

In [32]:
X_centered.mean(0)

array([-1.11022302e-17,  3.33066907e-17,  0.00000000e+00])

### Images

In [33]:
x = np.linspace(0, 5, 50)
y = np.linspace(0, 5, 50)[:, np.newaxis]

In [37]:
z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [ ]:
%matplotlib inline
import matplotlib