In [1]:
import numpy as np
import pandas as pd

In [2]:
x = np.arange(1, 6)

In [3]:
x

array([1, 2, 3, 4, 5])

In [4]:
x < 3

array([ True,  True, False, False, False])

In [5]:
x > 3

array([False, False, False,  True,  True])

In [6]:
x != 3

array([ True,  True, False,  True,  True])

In [7]:
(2 * x) == (x **2)

array([False,  True, False, False, False])

In [8]:
rng = np.random.RandomState(0)
x = rng.randint(10, size = (3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [9]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [10]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [11]:
np.count_nonzero(x < 6)

8

In [12]:
np.sum(x < 6)

8

In [13]:
np.sum(x < 6, axis = 1)

array([4, 2, 2])

In [14]:
np.any(x < 8)

True

In [15]:
np.all(x < 10)

True

In [16]:
np.all(x < 8, axis = 1)

array([ True, False,  True])

In [18]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [21]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])